-- ============================================================
-- VIMAK CRM V6.24.11 — MANUTENÇÃO / ORDEM DE SERVIÇO
-- Execute UMA VEZ no Supabase SQL Editor.
-- Seguro / idempotente / não apaga dados.
-- ============================================================

create table if not exists public.maintenance_orders (
 id uuid primary key default gen_random_uuid(),
 os_number bigint generated by default as identity unique,
 company_id uuid not null references public.companies(id) on delete cascade,
 after_sales_ticket_id uuid references public.after_sales_tickets(id) on delete set null,
 client_id uuid not null references public.clients(id) on delete restrict,
 proposal_id uuid references public.proposals(id) on delete set null,
 service_type text not null default 'Assistência técnica',
 priority text not null default 'Normal',
 status text not null default 'Agendada',
 scheduled_date date not null,
 start_time time,
 end_time time,
 technician text,
 address text,
 description text not null,
 diagnosis text,
 cost numeric(14,2) not null default 0,
 completed_at timestamptz,
 data jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create index if not exists idx_maintenance_company_date on public.maintenance_orders(company_id,scheduled_date);
create index if not exists idx_maintenance_company_status on public.maintenance_orders(company_id,status);
create index if not exists idx_maintenance_client on public.maintenance_orders(client_id);

alter table public.maintenance_orders enable row level security;

drop policy if exists tenant_isolation on public.maintenance_orders;
create policy tenant_isolation on public.maintenance_orders
for all to authenticated
using(company_id=public.current_company_id())
with check(company_id=public.current_company_id());

grant select,insert,update,delete on public.maintenance_orders to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into storage.buckets(id,name,public)
values('maintenance-photos','maintenance-photos',false)
on conflict(id) do update set public=false;

drop policy if exists "maintenance_photos_insert" on storage.objects;
create policy "maintenance_photos_insert"
on storage.objects for insert to authenticated
with check(bucket_id='maintenance-photos');

drop policy if exists "maintenance_photos_select" on storage.objects;
create policy "maintenance_photos_select"
on storage.objects for select to authenticated
using(bucket_id='maintenance-photos');

drop policy if exists "maintenance_photos_delete" on storage.objects;
create policy "maintenance_photos_delete"
on storage.objects for delete to authenticated
using(bucket_id='maintenance-photos');

notify pgrst,'reload schema';

select
 to_regclass('public.maintenance_orders') as tabela_os,
 exists(select 1 from storage.buckets where id='maintenance-photos') as bucket_fotos;
